//go:build ignore

package main

import (
	"bytes"
	"fmt"
	"os"
	"path/filepath"

	"github.com/Zxilly/cjv/internal/target"
)

func main() {
	root, err := filepath.Abs(filepath.Join("..", ".."))
	if err != nil {
		panic(err)
	}
	outPath := filepath.Join(root, "web", "src", "generated", "platforms.ts")
	if err := os.MkdirAll(filepath.Dir(outPath), 0o755); err != nil {
		panic(err)
	}

	var b bytes.Buffer
	b.WriteString("// Code generated by scripts/gen-platform-surfaces.go; DO NOT EDIT.\n\n")
	b.WriteString("export const SUPPORTED_PLATFORMS = [\n")
	for _, p := range target.SupportedHostPlatforms() {
		fmt.Fprintf(&b, "  { goos: '%s', goarch: '%s' },\n", p.GOOS, p.GOARCH)
	}
	b.WriteString("] as const\n\n")
	b.WriteString("export type SupportedPlatform = (typeof SUPPORTED_PLATFORMS)[number]\n")

	if err := os.WriteFile(outPath, b.Bytes(), 0o644); err != nil {
		panic(err)
	}
}
