//go:build openharmony

package selfsign

import (
	"bytes"
	"crypto/sha256"
	"debug/elf"
	"encoding/binary"
	"fmt"
	"testing"

	"github.com/stretchr/testify/assert"
	"github.com/stretchr/testify/require"
)

// Golden hashes were independently generated by selfsign.py from
// hqzing/ohos-selfsign@eee7eaf7ce18d6f5a543ac023df1d8b2a4a186a1.
// Fixtures include a load segment, NOBITS, appended data and extended entries.
func TestSignMatchesReference(t *testing.T) {
	for _, tc := range []struct {
		name          string
		extra, stride int
		digest        string
	}{
		{"small", 0, 64, "9b8bc1076522dc016c6519deecda2e2c55f30269354419ac0e3e000f807412bc"},
		{"appended", 600000, 64, "3a0479e87bf9914aa4903abda6164ce5a2413bad518ccf0f06c55ea89c204db2"},
		{"extended", 17, 72, "e951856e07ac520651f1644736c05df7999ec550bc2af220453a0c17f0c2a857"},
	} {
		t.Run(tc.name, func(t *testing.T) {
			input := testExecutable(t, tc.extra, tc.stride)
			original := bytes.Clone(input)
			output, err := Sign(input)
			require.NoError(t, err)
			assert.Equal(t, original, input, "Sign must not mutate its input")
			assert.Equal(t, tc.digest, fmt.Sprintf("%x", sha256.Sum256(output)))
			require.NoError(t, Verify(output))
			assert.Equal(t, input[64:], output[64:len(input)], "preserve segments, old table and appended bytes")
			_, err = Sign(output)
			require.ErrorContains(t, err, "already contains")
		})
	}
}

func TestVerifyRejectsCorruption(t *testing.T) {
	signed, err := Sign(testExecutable(t, 0, 64))
	require.NoError(t, err)
	for _, offset := range []int{128, 4096, 4104, 4120, 4360, 4392, len(signed) - 1} {
		t.Run(fmt.Sprint(offset), func(t *testing.T) {
			corrupt := bytes.Clone(signed)
			corrupt[offset] ^= 1
			require.Error(t, Verify(corrupt))
		})
	}
	for _, size := range []int{0, 63, 4096, len(signed) - 1} {
		require.Error(t, Verify(signed[:size]))
	}
}

func TestRejectMalformedELF(t *testing.T) {
	for _, tc := range []struct {
		name   string
		mutate func([]byte)
	}{
		{"section table outside file", func(b []byte) { binary.LittleEndian.PutUint64(b[40:], ^uint64(0)) }},
		{"section outside file", func(b []byte) { binary.LittleEndian.PutUint64(b[248:], 9999999) }},
		{"segment outside file", func(b []byte) { binary.LittleEndian.PutUint64(b[72:], 9999999) }},
		{"extended numbering", func(b []byte) { binary.LittleEndian.PutUint16(b[60:], 0) }},
		{"relocatable object", func(b []byte) { binary.LittleEndian.PutUint16(b[16:], uint16(elf.ET_REL)) }},
		{"big endian", func(b []byte) { b[5] = byte(elf.ELFDATA2MSB) }},
	} {
		t.Run(tc.name, func(t *testing.T) {
			input := testExecutable(t, 0, 64)
			tc.mutate(input)
			_, err := Sign(input)
			require.Error(t, err)
		})
	}
}

func TestNOBITSDoesNotGrowFile(t *testing.T) {
	input := testExecutable(t, 0, 64)
	// SHT_NOBITS has no file contents even if its virtual extent is large.
	binary.LittleEndian.PutUint64(input[312:], 1<<40)
	binary.LittleEndian.PutUint64(input[320:], 1<<40)
	output, err := Sign(input)
	require.NoError(t, err)
	assert.Len(t, output, 8544)
	require.NoError(t, Verify(output))
}

func TestMerkleReferenceVectors(t *testing.T) {
	for _, tc := range []struct {
		size int
		root string
	}{
		{0, "ad7facb2586fc6e966c004d7d1d16b024f5805ff7cb47c7a85dabd8b48892ca7"},
		{1, "ad7facb2586fc6e966c004d7d1d16b024f5805ff7cb47c7a85dabd8b48892ca7"},
		{4096, "d67c656e01756650d77717b0839985a056ec28ffe174601d690fc407a2ceffca"},
		{4097, "1f097ca96d9b4f62a0d0c1617831d9ce4f129c6b42ffc438358ee998b28bf3e2"},
		{524288, "1d5c63042908efc7369d03f4cb3db77afc917da1b7bd4941f4b1ed2ae1576459"},
		{528384, "8e3a3426cfdc1d0f3ef7ccd542ffb9ef715d8117df2dbb3f861e9d37ee3c4460"},
		{67108865, "f64750bf4fdd60a0504b1daace62231defefcc3d8cdda1b7f08e5940ad2c673d"},
	} {
		t.Run(fmt.Sprint(tc.size), func(t *testing.T) {
			data := make([]byte, tc.size)
			for i := range data {
				data[i] = byte(i % 251)
			}
			root, intermediate := merkleRoot(data, pageSize)
			assert.Equal(t, tc.root, fmt.Sprintf("%x", root))
			if tc.size == 67108865 {
				assert.Len(t, intermediate, 3800)
				assert.Equal(t, "429dbfcf9a150f4ae61a8c6eea5aa69b6ad82d36a1845c5f6a2a26967b9511ec", fmt.Sprintf("%x", sha256.Sum256(intermediate)))
			} else {
				assert.Empty(t, intermediate)
			}
		})
	}
}

func testExecutable(t *testing.T, extra, stride int) []byte {
	t.Helper()
	names := []byte("\x00.text\x00.bss\x00.shstrtab\x00")
	namesOffset := 160 + stride*4
	data := make([]byte, namesOffset+len(names)+extra)
	header := elf.Header64{
		Type: uint16(elf.ET_DYN), Machine: uint16(elf.EM_AARCH64), Version: 1,
		Entry: 0x10080, Phoff: 64, Shoff: 160, Ehsize: 64, Phentsize: 56,
		Phnum: 1, Shentsize: uint16(stride), Shnum: 4, Shstrndx: 3,
	}
	copy(header.Ident[:], "\x7fELF\x02\x01\x01")
	_, err := binary.Encode(data, binary.LittleEndian, header)
	require.NoError(t, err)
	program := elf.Prog64{Type: uint32(elf.PT_LOAD), Flags: uint32(elf.PF_R | elf.PF_X), Off: 128, Vaddr: 0x10080, Paddr: 0x10080, Filesz: 32, Memsz: 8192, Align: 4096}
	_, err = binary.Encode(data[64:], binary.LittleEndian, program)
	require.NoError(t, err)
	for i := range 32 {
		data[128+i] = byte(i)
	}
	sections := []elf.Section64{
		{},
		{Name: 1, Type: uint32(elf.SHT_PROGBITS), Flags: uint64(elf.SHF_ALLOC | elf.SHF_EXECINSTR), Addr: 0x10080, Off: 128, Size: 32, Addralign: 16},
		{Name: 7, Type: uint32(elf.SHT_NOBITS), Flags: uint64(elf.SHF_ALLOC | elf.SHF_WRITE), Addr: 0x100a0, Off: 160, Size: 8192, Addralign: 16},
		{Name: 12, Type: uint32(elf.SHT_STRTAB), Off: uint64(namesOffset), Size: uint64(len(names)), Addralign: 1},
	}
	for i, section := range sections {
		_, err := binary.Encode(data[160+i*stride:], binary.LittleEndian, section)
		require.NoError(t, err)
		for j := 64; j < stride; j++ {
			data[160+i*stride+j] = byte(0xa0 + i)
		}
	}
	copy(data[namesOffset:], names)
	for i := range extra {
		data[namesOffset+len(names)+i] = byte(i % 251)
	}
	return data
}
